name: home_project_ubuntu
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.14
  - aom=3.6.0
  - asttokens=3.0.0
  - attr=2.5.1
  - blas=1.0
  - boto3=1.37.10
  - botocore=1.37.10
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - comm=0.2.3
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.13.3
  - freetype-py=2.3.0
  - fribidi=1.0.10
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glib=2.84.0
  - glib-tools=2.84.0
  - graphite2=1.3.14
  - greenlet=3.2.4
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - harfbuzz=11.0.0
  - icu=75.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jmespath=1.0.1
  - joblib=1.5.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libavif=1.1.1
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libcap=2.71
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcups=2.3.3
  - libcurl=8.4.0
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.4
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.52.0
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.5
  - libprotobuf=5.29.3
  - librdkit=2025.03.5
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=256.9
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lmdb=0.9.29
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mesalib=25.0.4
  - metaflow=2.16.3
  - mkl=2025.0.0
  - mkl-service=2.4.0
  - mpg123=1.32.9
  - mysql=5.7.20
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nspr=4.37
  - nss=3.114
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.5.2
  - packaging=25.0
  - pandas=2.3.1
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=25.1
  - pixman=0.46.4
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - pycairo=1.28.0
  - pycparser=2.21
  - pygments=2.19.2
  - pyparsing=3.2.0
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyzmq=26.2.0
  - qt-main=5.15.15
  - rdkit=2025.03.5
  - readline=8.2
  - reportlab=4.4.1
  - requests=2.32.4
  - rlpycairo=0.2.0
  - s3transfer=0.11.2
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.17.0
  - spirv-tools=2025.1
  - sqlalchemy=2.0.42
  - sqlite=3.50.4
  - stack_data=0.6.3
  - tbb=2022.2.0
  - tbb-devel=2022.2.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toml=0.10.2
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==6.1.0
      - click==8.2.1
      - dnspython==2.7.0
      - email-validator==2.2.0
      - fastapi==0.116.1
      - fastapi-cli==0.0.8
      - fastapi-cloud-cli==0.1.5
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - jinja2==3.1.6
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - narwhals==2.1.2
      - protobuf==6.32.0
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - referencing==0.36.2
      - rich==14.1.0
      - rich-toolkit==0.15.0
      - rignore==0.6.4
      - rpds-py==0.27.0
      - sentry-sdk==2.35.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.47.2
      - streamlit==1.52.1
      - tenacity==9.1.2
      - typer==0.16.1
      - typing-inspection==0.4.1
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - watchdog==6.0.0
      - watchfiles==1.1.0
      - websockets==15.0.1
prefix: /home/andrea/miniconda3/envs/home_project_ubuntu
